events {}

http {
    server {
        listen 80;
        return 301 https://$host:8443$request_uri;
    }

    server {
        listen 8443 ssl;

        ssl_certificate     /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

        root /usr/share/nginx/html;
        index index.html;
    }
}
